project:
  type: website

website:
  navbar:
    background: primary
    left:
      - text: "Jurguen Bermudez"
        file: index.qmd
      - about.qmd 
      - posts.qmd
    
    right:
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/JurguenAndre
        
      - icon: github
        aria-label: github
        href: https://github.com/jurguenb

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

