project:
  type: website

website:
  navbar:
    background: dark
    left:
      - text: "Sobre mí" 
        file: about.qmd 
      - posts.qmd
    
    right:
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/JurguenAndre
        
      - icon: github
        aria-label: github
        href: https://github.com/jurguenb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


