project:
  type: website

website:
  navbar:
    background: dark
    left:
      - text: "Sobre mi" 
        file: index.qmd 
      - posts.qmd
    
    right:
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/JurguenAndre
        
      - icon: github
        aria-label: github
        href: https://github.com/jurguenb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    include-in-header: 
      text: |
        <!-- Google tag (gtag.js) -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-2KH7TS5JLS"></script>
        <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-2KH7TS5JLS');
        </script>

editor: visual


